export const USER_SET_USER = 'USER_SET_USER';
export const USER_ADD_MEMBER = 'USER_ADD_MEMBER';
export const USER_SET_CURRENT_USER = 'USER_CHANGE_CURRENT_USER';
export const USER_UPDATE_BY_NAME = 'USER_UPDATE_BY_NAME';